<a href="https://colab.research.google.com/github/sksatvikkumar/DATA110-Cybersecurity-Capstone/blob/main/Pandas_class_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = ["Siddhant" , "Tessica" , "Ritesh" , "Srivardhan"]
mydata = pd.Series(data, index = ["a", "b", "c", "d"])
mydata

a      Siddhant
b       Tessica
c        Ritesh
d    Srivardhan
dtype: object

In [ ]:
mydata = pd.Series("10", index = list(range(0,6)))
mydata

0    10
1    10
2    10
3    10
4    10
5    10
dtype: object

In [ ]:
data = {"Name" : ["A" , "B" , "C"],
        "Age" : [22,23,24],
        "Education" : ["BBA", "MS", "Btech"]
}

In [ ]:
df = pd.DataFrame (data)
df

  Name  Age Education
0    A   22       BBA
1    B   23        MS
2    C   24     Btech

In [ ]:
DF2 = df.loc[(df["AMOUNT"]>1000) & (df["EDUCATION"]==1)].sort_values